#!/bin/sh
# zabbix-server エントリポイント [FR3.2]。公式イメージとの環境変数互換性を維持する。
#
# 公式 zabbix/zabbix-server-mysql イメージと同じ環境変数名(DB_SERVER_HOST,
# DB_SERVER_PORT, MYSQL_USER, MYSQL_PASSWORD, MYSQL_DATABASE, ZBX_DBTLSCONNECT等)
# から /etc/zabbix/zabbix_server.conf を生成し、フォアグラウンドでzabbix_serverを
# 起動する。LogType=consoleによりログはすべて標準出力/標準エラーへ出力する。

set -eu

CONFIG_FILE="/etc/zabbix/zabbix_server.conf"

: "${DB_SERVER_HOST:=mysql-server}"
: "${DB_SERVER_PORT:=3306}"
: "${MYSQL_USER:=zabbix}"
: "${MYSQL_DATABASE:=zabbix}"

fail() {
	echo "**** ERROR: $1" >&2
	echo "**** Exiting..." >&2
	exit 1
}

if [ -z "${MYSQL_PASSWORD:-}" ]; then
	fail "MYSQL_PASSWORD is not set. This variable is mandatory for Zabbix server to connect to the database."
fi

echo "**** Generating ${CONFIG_FILE} from environment variables..."

cat > "${CONFIG_FILE}" <<CONF
# Generated by docker/server/entrypoint.sh at container start — do not edit by hand, it is
# overwritten on every restart.

LogType=console
PidFile=/run/zabbix/zabbix_server.pid
SocketDir=/run/zabbix

DBHost=${DB_SERVER_HOST}
DBPort=${DB_SERVER_PORT}
DBName=${MYSQL_DATABASE}
DBUser=${MYSQL_USER}
DBPassword=${MYSQL_PASSWORD}

AlertScriptsPath=/var/lib/zabbix/alertscripts
ExternalScripts=/var/lib/zabbix/externalscripts
LoadModulePath=/var/lib/zabbix/modules
ExportDir=/var/lib/zabbix/export
CONF

# 未設定(既定)の場合はDBTLSConnect行を生成しない — TLSなしで接続する。公式イメージと
# 同じ変数名(ZBX_DBTLSCONNECT等)を使うことで、公式イメージからの切替時に追加設定なしで
# 同じ挙動を再現できる(NFR4 環境変数互換性)。
if [ -n "${ZBX_DBTLSCONNECT:-}" ]; then
	{
		echo ""
		echo "DBTLSConnect=${ZBX_DBTLSCONNECT}"
		[ -n "${ZBX_DBTLSCAFILE:-}" ] && echo "DBTLSCAFile=${ZBX_DBTLSCAFILE}"
		[ -n "${ZBX_DBTLSCERTFILE:-}" ] && echo "DBTLSCertFile=${ZBX_DBTLSCERTFILE}"
		[ -n "${ZBX_DBTLSKEYFILE:-}" ] && echo "DBTLSKeyFile=${ZBX_DBTLSKEYFILE}"
	} >> "${CONFIG_FILE}"
fi

echo "**** Starting Zabbix server..."
exec su-exec zabbix zabbix_server --foreground -c "${CONFIG_FILE}"
