#!/bin/sh
# zabbix-agent2 エントリポイント [FR3.2]。公式イメージとの環境変数互換性を維持する。
#
# 公式 zabbix/zabbix-agent2 イメージと同じ環境変数名(ZBX_SERVER_HOST, ZBX_HOSTNAME)から
# /etc/zabbix/zabbix_agent2.conf を生成し、フォアグラウンドでzabbix_agent2を起動する。

set -eu

CONFIG_FILE="/etc/zabbix/zabbix_agent2.conf"

: "${ZBX_SERVER_HOST:=zabbix-server}"

echo "**** Generating ${CONFIG_FILE} from environment variables..."

{
	echo "# Generated by docker/agent2/entrypoint.sh at container start — do not edit by hand, it is"
	echo "# overwritten on every restart."
	echo ""
	echo "LogType=console"
	echo "PidFile=/run/zabbix/zabbix_agent2.pid"
	echo "ControlSocket=/run/zabbix/agent.sock"
	echo ""
	echo "Server=${ZBX_SERVER_HOST}"
	echo "ServerActive=${ZBX_SERVER_HOST}"
	echo ""
	if [ -n "${ZBX_HOSTNAME:-}" ]; then
		echo "Hostname=${ZBX_HOSTNAME}"
	fi
	echo "EnablePersistentBuffer=0"
} > "${CONFIG_FILE}"

echo "**** Starting Zabbix agent2..."
exec zabbix_agent2 --foreground -c "${CONFIG_FILE}"
