#!/bin/sh
# zabbix-agent2 エントリポイント [FR3.2]。公式 zabbix/zabbix-agent2 イメージと同じ環境変数から
# /etc/zabbix/zabbix_agent2.conf を生成し、zabbix_agent2 をフォアグラウンドで起動する。
# 公式と同様に、未指定または空の変数はZabbix自身の既定値のままにする。LogType=console で、ログは
# ファイルではなく標準出力へ出す。
#
# 対応するもの: 下のSCALARSの表にあるスカラー値のパラメータ、ZBX_SERVER_HOST/ZBX_SERVER_PORT/
# ZBX_PASSIVESERVERS/ZBX_ACTIVESERVERS、ZBX_PASSIVE_ALLOW/ZBX_ACTIVE_ALLOW、ZBX_HOSTNAME、
# ZBX_ENABLEPERSISTENTBUFFER、ZBX_ENABLESTATUSPORT、TLSのパラメータ(値そのものでの指定を含む)。
# 対応しないもの: このイメージが扱わないZBX_*は、起動時に警告を出して無視したことを必ず知らせる
# (例えばZBX_TLSCONNECTが黙って落ちると、暗号化されないまま動いてしまうため)。

set -eu

CONFIG_FILE="/etc/zabbix/zabbix_agent2.conf"
HOME_DIR="/var/lib/zabbix"
ENC_DIR="${HOME_DIR}/enc"
INTERNAL_ENC_DIR="${HOME_DIR}/enc_internal"
NL='
'

# <公式の環境変数>:<zabbix_agent2.conf のパラメータ>(いずれも 6.0.48 のzabbix_agent2.confにある)
SCALARS="
ZBX_DEBUGLEVEL:DebugLevel
ZBX_TIMEOUT:Timeout
ZBX_SOURCEIP:SourceIP
ZBX_LISTENIP:ListenIP
ZBX_LISTENPORT:ListenPort
ZBX_HOSTNAMEITEM:HostnameItem
ZBX_METADATA:HostMetadata
ZBX_METADATAITEM:HostMetadataItem
ZBX_HOSTINTERFACE:HostInterface
ZBX_HOSTINTERFACEITEM:HostInterfaceItem
ZBX_REFRESHACTIVECHECKS:RefreshActiveChecks
ZBX_BUFFERSEND:BufferSend
ZBX_BUFFERSIZE:BufferSize
ZBX_PERSISTENTBUFFERPERIOD:PersistentBufferPeriod
ZBX_PLUGINTIMEOUT:PluginTimeout
ZBX_UNSAFEUSERPARAMETERS:UnsafeUserParameters
ZBX_FORCEACTIVECHECKSONSTART:ForceActiveChecksOnStart
ZBX_LOGREMOTECOMMANDS:Plugins.SystemRun.LogRemoteCommands
ZBX_MAXLINESPERSECOND:Plugins.Log.MaxLinesPerSecond
ZBX_ALLOWKEY:AllowKey
ZBX_DENYKEY:DenyKey
ZBX_TLSCONNECT:TLSConnect
ZBX_TLSACCEPT:TLSAccept
ZBX_TLSSERVERCERTISSUER:TLSServerCertIssuer
ZBX_TLSSERVERCERTSUBJECT:TLSServerCertSubject
ZBX_TLSPSKIDENTITY:TLSPSKIdentity
"

# <パラメータ>:<ファイルのパスを入れる変数>:<ファイルの中身そのものを入れる変数>
TLS_FILES="
TLSCAFile:ZBX_TLSCAFILE:ZBX_TLSCA
TLSCRLFile:ZBX_TLSCRLFILE:ZBX_TLSCRL
TLSCertFile:ZBX_TLSCERTFILE:ZBX_TLSCERT
TLSKeyFile:ZBX_TLSKEYFILE:ZBX_TLSKEY
TLSPSKFile:ZBX_TLSPSKFILE:ZBX_TLSPSK
"

fail() {
	echo "**** ERROR: $1" >&2
	echo "**** Exiting..." >&2
	exit 1
}

zbx_env_names() {
	env | sed -n 's/^\(ZBX_[A-Za-z0-9_]*\)=.*/\1/p'
}

# conf_set <パラメータ> <値> — 値が空でなければ設定ファイルへ追記する。
conf_set() {
	[ -n "$2" ] || return 0
	case "$2" in
		*"${NL}"*) fail "the value for $1 contains a line break" ;;
	esac
	printf '%s=%s\n' "$1" "$2" >> "${CONFIG_FILE}"
}

env_value() {
	printenv "$1" || true
}

# bool_value <変数> <既定> — true/false(大文字小文字は問わない)を返す。それ以外はfalse扱い。
bool_value() {
	value="$(env_value "$1" | tr '[:upper:]' '[:lower:]')"
	[ -n "${value}" ] || value="$2"
	[ "${value}" = "true" ] && echo true || echo false
}

# join_list <値>... — 空でない値だけをカンマでつなぐ。
join_list() {
	out=""
	for item in "$@"; do
		[ -n "${item}" ] || continue
		out="${out:+${out},}${item}"
	done
	printf '%s' "${out}"
}

# tls_file <パラメータ> <パスの変数> <中身の変数> — 中身の変数に値があれば enc_internal 配下のファイルへ
# 書き出してそれを使い(こちらが優先)、無ければパスの変数を使う(相対パスは enc ボリューム内を探す)。
tls_file() {
	file="$(env_value "$2")"
	content="$(env_value "$3")"
	if [ -n "${content}" ]; then
		file="${INTERNAL_ENC_DIR}/$1"
		( umask 077 && printf '%s\n' "${content}" > "${file}" )
	elif [ -n "${file}" ]; then
		case "${file}" in
			/*) ;;
			*) file="${ENC_DIR}/${file}" ;;
		esac
	fi
	conf_set "$1" "${file}"
}

: "${ZBX_SERVER_HOST:=zabbix-server}"

# 公式と同じ: Server(パッシブチェックで接続を許すサーバー)はZBX_SERVER_HOSTとZBX_PASSIVESERVERS、
# ServerActive(アクティブチェックの送信先)はZBX_SERVER_HOST[:ZBX_SERVER_PORT]とZBX_ACTIVESERVERS。
active_host="${ZBX_SERVER_HOST}"
[ -z "${ZBX_SERVER_PORT:-}" ] || active_host="${ZBX_SERVER_HOST}:${ZBX_SERVER_PORT}"

echo "**** Generating ${CONFIG_FILE} from environment variables..."

cat > "${CONFIG_FILE}" <<'CONF'
# Generated by docker/agent2/entrypoint.sh at container start — do not edit by hand, it is
# overwritten on every restart.

LogType=console
PidFile=/run/zabbix/zabbix_agent2.pid
ControlSocket=/run/zabbix/agent.sock
CONF

if [ "$(bool_value ZBX_PASSIVE_ALLOW true)" = "true" ]; then
	conf_set Server "$(join_list "${ZBX_SERVER_HOST}" "$(env_value ZBX_PASSIVESERVERS)")"
fi
if [ "$(bool_value ZBX_ACTIVE_ALLOW true)" = "true" ]; then
	conf_set ServerActive "$(join_list "${active_host}" "$(env_value ZBX_ACTIVESERVERS)")"
fi

conf_set Hostname "$(env_value ZBX_HOSTNAME)"

# 公式の既定はfalse(0)。true/falseは1/0へ直し、数字はそのまま渡す。
persistent="$(env_value ZBX_ENABLEPERSISTENTBUFFER | tr '[:upper:]' '[:lower:]')"
case "${persistent}" in
	true | 1) conf_set EnablePersistentBuffer 1; conf_set PersistentBufferFile "${HOME_DIR}/buffer/agent2.db" ;;
	*) conf_set EnablePersistentBuffer 0 ;;
esac

if [ "$(bool_value ZBX_ENABLESTATUSPORT false)" = "true" ]; then
	conf_set StatusPort 31999
fi

for pair in ${SCALARS}; do
	conf_set "${pair#*:}" "$(env_value "${pair%%:*}")"
done

for entry in ${TLS_FILES}; do
	key="${entry%%:*}"
	rest="${entry#*:}"
	tls_file "${key}" "${rest%%:*}" "${rest#*:}"
done

# 設定されているのにこのイメージが扱わない変数を、運用者へ知らせる。
known=" ZBX_SERVER_HOST ZBX_SERVER_PORT ZBX_PASSIVESERVERS ZBX_ACTIVESERVERS ZBX_PASSIVE_ALLOW ZBX_ACTIVE_ALLOW ZBX_HOSTNAME ZBX_ENABLEPERSISTENTBUFFER ZBX_ENABLESTATUSPORT ZBX_CLEAR_ENV"
for pair in ${SCALARS}; do
	known="${known} ${pair%%:*}"
done
for entry in ${TLS_FILES}; do
	rest="${entry#*:}"
	known="${known} ${rest%%:*} ${rest#*:}"
done
for name in $(zbx_env_names); do
	case "${known} " in
		*" ${name} "*) ;;
		*) echo "**** WARNING: ${name} is set but is not supported by this image; it is ignored." >&2 ;;
	esac
done

# 公式のイメージと同じく、zabbix_agent2 が動く環境からZBX_*を取り除く(PSKや鍵の中身が入っている
# ことがあるため)。ZBX_CLEAR_ENV=false なら残す。
if [ "${ZBX_CLEAR_ENV:-true}" != "false" ]; then
	for name in $(zbx_env_names); do
		unset "${name}"
	done
fi

echo "**** Starting Zabbix agent2..."
exec zabbix_agent2 --foreground -c "${CONFIG_FILE}"
