#!/bin/sh
# zabbix-proxy(SQLite3) エントリポイント [FR3.2][BR5.1]。公式イメージとの環境変数互換性を維持する。
#
# 公式 zabbix/zabbix-proxy-sqlite3 イメージと同じ環境変数名(ZBX_SERVER_HOST,
# ZBX_HOSTNAME等)から /etc/zabbix/zabbix_proxy.conf を生成する。ローカルバッファは
# SQLite3のみを使用する(BR5.1の例外規定)。DBNameはバッファファイルへの絶対パスであり、
# MySQL接続情報は一切扱わない。

set -eu

CONFIG_FILE="/etc/zabbix/zabbix_proxy.conf"
DB_FILE="/var/lib/zabbix/db_data/zabbix_proxy.db"

: "${ZBX_SERVER_HOST:=zabbix-server}"
# プロキシ名は公式イメージと同じ ZBX_HOSTNAME で受け取る。以前のこのイメージは
# ZBX_PROXY_HOSTNAME だけを読んでおり、公式の指定方法(ZBX_HOSTNAME)で渡した名前が黙って
# 無視され、サーバー側で「proxy not found」になっていた。既存の利用者のため
# ZBX_PROXY_HOSTNAME も別名として残す(両方指定なら公式のZBX_HOSTNAMEを優先)。
: "${ZBX_HOSTNAME:=${ZBX_PROXY_HOSTNAME:-zabbix-proxy}}"

echo "**** Generating ${CONFIG_FILE} from environment variables..."

cat > "${CONFIG_FILE}" <<CONF
# Generated by docker/proxy/entrypoint.sh at container start — do not edit by hand, it is
# overwritten on every restart.

LogType=console
PidFile=/run/zabbix/zabbix_proxy.pid
SocketDir=/run/zabbix

Server=${ZBX_SERVER_HOST}
Hostname=${ZBX_HOSTNAME}

DBName=${DB_FILE}

ExternalScripts=/var/lib/zabbix/externalscripts
CONF

echo "**** Starting Zabbix proxy (SQLite3 local buffer)..."
exec su-exec zabbix zabbix_proxy --foreground -c "${CONFIG_FILE}"
