#!/bin/sh
# zabbix-web(nginx + PHP-FPM) エントリポイント [FR3.2]。公式イメージとの環境変数互換性を維持する。
#
# 公式 zabbix/zabbix-web-nginx-mysql イメージと同じ環境変数名(DB_SERVER_HOST,
# MYSQL_USER, MYSQL_PASSWORD, MYSQL_DATABASE, ZBX_SERVER_HOST, ZBX_SERVER_NAME,
# PHP_TZ)から /usr/share/zabbix/conf/zabbix.conf.php を生成する。
# PHP-FPMをバックグラウンドで起動し、nginxをフォアグラウンドでexecする
# (このコンテナ内では2プロセスの単純な起動順序管理のみを行い、専用の
# プロセスマネージャ(supervisord等)は導入しない)。

set -eu

CONFIG_FILE="/usr/share/zabbix/conf/zabbix.conf.php"
PHP_FPM_BIN="${PHP_FPM_BIN:-php-fpm83}"

: "${DB_SERVER_HOST:=mysql-server}"
: "${DB_SERVER_PORT:=3306}"
: "${MYSQL_USER:=zabbix}"
: "${MYSQL_DATABASE:=zabbix}"
: "${ZBX_SERVER_HOST:=zabbix-server}"
: "${ZBX_SERVER_PORT:=10051}"
: "${ZBX_SERVER_NAME:=}"
: "${PHP_TZ:=UTC}"

fail() {
	echo "**** ERROR: $1" >&2
	echo "**** Exiting..." >&2
	exit 1
}

if [ -z "${MYSQL_PASSWORD:-}" ]; then
	fail "MYSQL_PASSWORD is not set. This variable is mandatory for Zabbix web to connect to the database."
fi

echo "**** Applying PHP_TZ=${PHP_TZ} to date.timezone..."
# `sed -i` writes a temp file into the target's own directory before renaming
# it into place, which needs write access on the DIRECTORY, not just the file.
# The image intentionally chowns only this one file to the non-root zabbix
# user (least-privilege; the directory itself stays root-owned), so `sed -i`
# fails here with a permission error. Read + rewrite through a shell variable
# instead: that only needs to open the already zabbix-owned file for writing,
# never touching the directory.
ZBX_INI_CONTENT="$(sed "s/^date.timezone = .*/date.timezone = ${PHP_TZ}/" /etc/php83/conf.d/99-zabbix.ini)"
printf '%s\n' "${ZBX_INI_CONTENT}" > /etc/php83/conf.d/99-zabbix.ini

echo "**** Generating ${CONFIG_FILE} from environment variables..."

cat > "${CONFIG_FILE}" <<CONF
<?php
// Generated by docker/web/entrypoint.sh at container start — do not edit by hand, it is
// overwritten on every restart.

global \$DB;

\$DB['TYPE']     = 'MYSQL';
\$DB['SERVER']   = '${DB_SERVER_HOST}';
\$DB['PORT']     = '${DB_SERVER_PORT}';
\$DB['DATABASE'] = '${MYSQL_DATABASE}';
\$DB['USER']     = '${MYSQL_USER}';
\$DB['PASSWORD'] = '${MYSQL_PASSWORD}';
\$DB['SCHEMA']   = '';

\$DB['ENCRYPTION']  = false;
\$DB['KEY_FILE']    = '';
\$DB['CERT_FILE']   = '';
\$DB['CA_FILE']     = '';
\$DB['VERIFY_HOST'] = false;
\$DB['CIPHER_LIST'] = '';

\$ZBX_SERVER      = '${ZBX_SERVER_HOST}';
\$ZBX_SERVER_PORT = '${ZBX_SERVER_PORT}';
\$ZBX_SERVER_NAME = '${ZBX_SERVER_NAME}';

\$IMAGE_FORMAT_DEFAULT = IMAGE_FORMAT_PNG;
CONF

echo "**** Starting PHP-FPM..."
"${PHP_FPM_BIN}" --nodaemonize &

echo "**** Starting nginx..."
# nginxはconfig解析より前の起動処理(マスタープロセスのブートストラップ)で、
# nginx.conf内のerror_logディレクティブが効くよりも先にコンパイル時既定のログパス
# (/var/lib/nginx/logs/error.log、root所有)を開こうとする。非rootのzabbixユーザー
# では書き込めず[emerg]で即座に落ちる(実機テストで判明。nginx.conf側のerror_log
# 指定だけでは防げない)。`-e`コマンドラインオプションはconfig解析より前に有効になる
# ため、これで確実にstderrへ向ける。
exec nginx -e /dev/stderr -g "daemon off;"
